export const cards = [
  {
    preTitle: "Квест для истинных любителей истории.",
    title: "Разгадай Тверь",
    text: "12 вопросов. 3 категории. 4 минуты. Только ты и история Тверской области.",
    picSrc: "/images/QuizCards/e5065ee379a684fec367ed0338938ea3.png",
    alt: "Разгадай Тверь",
    cardGlobalState: "quizRules",
    info: {installation: "right",
    type: "mode",
    data: "victorina",
  },
  },
  {
    preTitle: "Конструктор для любителей головоломок.",
    title: "Игра",
    text: "Используй набор деталей и собери виртуальную модель Иволги.",
    picSrc: "/images/QuizCards/57fddd1342fb684ec641252d6de345e5.png",
    alt: "Игра ",
    cardGlobalState: "4",
    info: {installation: "right",
    type: "mode",
    data: "puzzle",
  },
  },
  {
    preTitle: "Квест для истинных любителей истории.",
    title: "Игра",
    text: "12 вопросов. 3 категории. 4 минуты. Только ты и история Тверской области.",
    picSrc: "/images/QuizCards/b364b2dcb07b219f03cbb4cc67d8fbdc.png",
    alt: "Игра",
    cardGlobalState: "5",
    info: {installation: "right",
    type: "mode",
    data: "game",
  },
  },
  {
    preTitle: "Квест для истинных любителей истории.",
    title: "Собери Иволгу",
    text: "Используй набор деталей и собери виртуальную модель Иволги.",
    picSrc: "/images/QuizCards/img.png",
    alt: "Собери Иволгу",
    cardGlobalState: "6 ",
    info: {installation: "right",
    type: "mode",
    data: "ivolga",
  },
  },
];
