export const cards = [
  {
    title: "Тверской императорский дворец",
    text: "Загадочный памятник А.С. Пушкину, Венгерский мост, любимый памятник посла Индии - и это еще не весь список интересных достопримечательностей на этом маршруте..",
    picSrc: "/images/cards/putevoi.png",
    alt: "Тверской императорский дворец",
    zigZagSrc: "/images/cards/zigzag.png",
    cardNumber: '1',
    info: {installation: "velo",
      type: "level",
      data: "level1_start",
    },
  },
  {
    title: "Мультимедийный исторический парк «Россия-моя история»",
    text: "Маршрут позволит увидеть знаковые объекты города и расскажет истории их создания. Это позволит лучше понять прошлое и настоящее всего региона.",
    picSrc: "/images/cards/museum2.png",
    alt: "Мультимедийный исторический парк «Россия-моя история»",
    zigZagSrc: "/images/cards/zigzag.png",
    cardNumber: '2',
    info: {installation: "velo",
      type: "level",
      data: "level2_start",
    },
  },
  {
    title: "Ржевский мемориал Советскому солдату",
    text: "Великий подвиг советских воинов, увековеченный в монументальном мемориале. Это стоит увидеть.",
    picSrc: "/images/cards/soldier2.png",
    alt: "Ржевский мемориал Советскому солдату",
    zigZagSrc: "/images/cards/zigzag.png",
    cardNumber: '3',
    info: { installation: "velo",
      type: "level",
      data: "level3_start",
    },
  },
];
