export const cards = [
  {
    title: "Путевой дворец",
    text: "Значимость этих проблем настолько очевидна, что внедрение современных методик требует анализа новых.",
    picSrc: "/images/putevoi.png",
    alt: "Путевой дворец",
    zigZagSrc: "/images/zigzag.png",
    info: {installation: "velo",
      type: "level",
      data: "level1_start",
    },
  },
  {
    title: "Музей России",
    text: "Значимость этих проблем настолько очевидна, что внедрение современных методик требует анализа новых.",
    picSrc: "/images/museum2.png",
    alt: "Музей России",
    zigZagSrc: "/images/zigzag.png",
    info: {installation: "velo",
      type: "level",
      data: "level2_start",
    },
  },
  {
    title: "Ржевский солдат",
    text: "Значимость этих проблем настолько очевидна, что внедрение современных методик требует анализа новых.",
    picSrc: "/images/soldier.png",
    alt: "Ржевский солдат",
    zigZagSrc: "/images/zigzag.png",
    info: { installation: "velo",
      type: "level",
      data: "level3_start",
    },
  },
];
