export const details = [
  {
    id: 1,
    name: "Кузов",
    description:
      "Массивный надежный элемент, который принимает на себя всю массу вагона и пассажиров с их багажом.",
    picSrc: "/images/train/detail_01.png",
    alt: "Тележки",
  },
  {
    id: 2,
    name: "Окраска",
    description: "Окраска",
    picSrc: "/images/train/detail_02.png",
    alt: "Рама баржи",
  },
  {
    id: 3,
    name: "Крэш-система",
    description: "описание креш системы",
    picSrc: "/images/train/detail_03.png",
    alt: "Двери и окна",
  },

  {
    id: 4,
    name: "Кабина",
    description: "Описание кабины",
    picSrc: "/images/train/detail_04.png",
    alt: "Тележки",
  },
  {
    id: 5,
    name: "Двери и окна",
    description: "Описание дверей и окон",
    picSrc: "/images/train/detail_05.png",
    alt: "Рама баржи",
  },
  {
    id: 6,
    name: "Электрооборудование",
    description: "Описание электрооборудования",
    picSrc: "/images/train/detail_06.png",
    alt: "Двери и окна",
  },
  {
    id: 7,
    name: "Внутреннее оборудование",
    description: "Описание внутреннего оборудования",
    picSrc: "/images/train/detail_07.png",
    alt: "Тележки",
  },
  {
    id: 8,
    name: "Подвогонное оборудование",
    description: "Описание подвогонного оборудования",
    picSrc: "/images/train/detail_08.png",
    alt: "Рама баржи",
  },
  {
    id: 9,
    name: "Интерьер",
    description: "Описание интерьера",
    picSrc: "/images/train/detail_09.png",
    alt: "Двери и окна",
  },
  {
    id: 10,
    name: "Тележки",
    description: "Описание тележек",
    picSrc: "/images/train/detail_10.png",
    alt: "Рама баржи",
  },
  {
    id: 11,
    name: "Упс эта деталь совсем не от Иволги",
    description: "",
    picSrc: null,
    alt: "Упс эта деталь совсем не от Иволги",
  },
  {
    id: 12,
    name: "Упс эта деталь совсем не от Иволги",
    description: "",
    picSrc: null,
    alt: "Упс эта деталь совсем не от Иволги",
  },
  {
    id: 13,
    name: "Упс эта деталь совсем не от Иволги",
    description: "",
    picSrc: null,
    alt: "Упс эта деталь совсем не от Иволги",
  },
  {
    id: 14,
    name: "Упс эта деталь совсем не от Иволги",
    description: "",
    picSrc: null,
    alt: "Упс эта деталь совсем не от Иволги",
  },
  {
    id: 15,
    name: "Упс эта деталь совсем не от Иволги",
    description: "",
    picSrc: null,
    alt: "Упс эта деталь совсем не от Иволги",
  },
];
